spring.application.name=roomFit
spring.profiles.include=secret


spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core=DEBUG

# ?? ?? ???
spring.servlet.multipart.max-file-size=50MB
# ?? ?? ???
spring.servlet.multipart.max-request-size=50MB

firebase.service-account.path=firebase/firebase-service-account.json