// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02vdkGUDVtGSUZZuZ8pcspcFOXeXBlHc',
    appId: '1:737910084682:web:11cc8d3938c0715a2a82b3',
    messagingSenderId: '737910084682',
    projectId: 'roomfit-dffa0',
    authDomain: 'roomfit-dffa0.firebaseapp.com',
    storageBucket: 'roomfit-dffa0.firebasestorage.app',
    measurementId: 'G-83FH7ZPLQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3DPy7hzejSOuqIXu1WTKEAaYZR9uuwTs',
    appId: '1:737910084682:android:9c07fc5ad582e1772a82b3',
    messagingSenderId: '737910084682',
    projectId: 'roomfit-dffa0',
    storageBucket: 'roomfit-dffa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArMTeTgdQLqv14I-BV2XKd9u0YsGqkARU',
    appId: '1:737910084682:ios:715930a30c5398692a82b3',
    messagingSenderId: '737910084682',
    projectId: 'roomfit-dffa0',
    storageBucket: 'roomfit-dffa0.firebasestorage.app',
    iosBundleId: 'com.example.roomfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArMTeTgdQLqv14I-BV2XKd9u0YsGqkARU',
    appId: '1:737910084682:ios:e8c6cfe305abe6b82a82b3',
    messagingSenderId: '737910084682',
    projectId: 'roomfit-dffa0',
    storageBucket: 'roomfit-dffa0.firebasestorage.app',
    iosBundleId: 'com.example.roomfitPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC02vdkGUDVtGSUZZuZ8pcspcFOXeXBlHc',
    appId: '1:737910084682:web:e2e2d7ff247d36be2a82b3',
    messagingSenderId: '737910084682',
    projectId: 'roomfit-dffa0',
    authDomain: 'roomfit-dffa0.firebaseapp.com',
    storageBucket: 'roomfit-dffa0.firebasestorage.app',
    measurementId: 'G-238HSMB3R9',
  );

}